// أسماء التشطيبات (ثنائية اللغة) ولون الدائرة المقابلة
const FINISH = {
  black: { name: { ar: 'أسود مطفي', en: 'Matte black' }, swatch: '#1a1a1a' },
  chrome: { name: { ar: 'كروم لامع', en: 'Polished chrome' }, swatch: 'linear-gradient(135deg,#e9e9f2,#9aa0b5)' },
  gray: { name: { ar: 'رمادي فاخر', en: 'Luxe gray' }, swatch: '#5b5b6b' },
  gold: { name: { ar: 'ذهبي تيتانيوم', en: 'Titanium gold' }, swatch: 'linear-gradient(135deg,#f5e6a8,#c9a24a)' },
  rosegold: { name: { ar: 'روز جولد', en: 'Rose gold' }, swatch: 'linear-gradient(135deg,#f3c9c0,#c98a7a)' },
  white: { name: { ar: 'أبيض لامع', en: 'Glossy white' }, swatch: 'linear-gradient(135deg,#ffffff,#dfe2ea)' },
}

const yrs = { ar: 'الضمان', en: 'Warranty' }
const y5 = { ar: '5 سنوات', en: '5 years' }

// المنتجات (حقول ثنائية اللغة)
export const PRODUCTS = [
  {
    id: 'mixer-chrome', collection: 'mixers',
    title: { ar: 'خلاط المغسلة الكروم', en: 'Chrome Basin Mixer' },
    tagline: { ar: 'انسيابية كروم لامعة بمقبض جانبي مريح', en: 'Polished chrome flow with a comfortable side lever' },
    desc: { ar: 'خلاط مغسلة بتشطيب كروم لامع ومخرج انسيابي، لمسة عصرية راقية لأي مغسلة.', en: 'A basin mixer with a polished chrome finish and a flowing spout — a refined modern touch for any washbasin.' },
    specs: [
      [{ ar: 'التشطيب', en: 'Finish' }, { ar: 'كروم لامع', en: 'Polished chrome' }],
      [{ ar: 'التدفّق', en: 'Flow' }, { ar: '6 لتر/دقيقة', en: '6 L/min' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome'], images: { chrome: '/products/mixer-chrome.webp' },
    // معرض صور المنتج (تُستبدل الصور المفقودة تلقائياً — أضف الملفات لتفعيلها)
    gallery: [
      '/products/mixer-chrome-1.webp',
      '/products/mixer-chrome-2.webp',
      '/products/mixer-chrome-3.webp',
      '/products/mixer-chrome-4.webp',
    ],
    // وصف مطوّل فاخر يظهر أسفل صفحة المنتج
    story: {
      ar: 'خلاط نحتيّ بخطوط هندسية صارمة وتشطيب كروم مرآوي يعكس الضوء كأنه جوهرة في حمّامك. صُمّم ليجمع بين صلابة الحضور ونعومة التدفّق، فكل زاوية فيه محسوبة بدقّة، وكل انعكاس مدروس ليمنح مساحتك إحساساً فندقياً راقياً يدوم.',
      en: 'A sculptural mixer with strict geometric lines and a mirror-chrome finish that catches light like a jewel in your bathroom. Engineered to unite a solid presence with a gentle flow — every edge precisely measured, every reflection considered to give your space a refined, lasting hotel feel.',
    },
  },
  {
    id: 'basin', collection: 'mixers',
    title: { ar: 'خلاط المغسلة الأسود', en: 'Black Basin Mixer' },
    tagline: { ar: 'مقبض جانبي مريح ومخرج انسيابي راقٍ', en: 'A comfortable side lever and an elegant flowing spout' },
    desc: { ar: 'مخلط حوض متوازن بمقبض جانبي مريح ومخرج انسيابي، لمسة نهائية راقية لأي مغسلة.', en: 'A balanced basin mixer with a comfortable side lever and a flowing spout — an elegant finishing touch for any washbasin.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'التدفّق', en: 'Flow' }, { ar: '6 لتر/دقيقة', en: '6 L/min' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['black'], images: { black: '/products/faucet-basin-black.webp' },
  },
  {
    id: 'spray-gold', collection: 'sprays',
    title: { ar: 'نظام الدش الذهبي', en: 'Gold Shower System' },
    tagline: { ar: 'مرش علوي مطري ويدوي بتشطيب ذهبي فاخر', en: 'Rain overhead + handheld head in a luxe gold finish' },
    desc: { ar: 'نظام دش متكامل بمرش علوي واسع ورأس يدوي متعدّد الأوضاع، بتشطيب ذهبي يمنح حمّامك فخامة استثنائية.', en: 'A complete shower system with a wide rain head and a multi-mode handheld spray, in a gold finish that lends your bathroom exceptional luxury.' },
    specs: [
      [{ ar: 'المرش', en: 'Heads' }, { ar: 'علوي + يدوي', en: 'Overhead + handheld' }],
      [{ ar: 'الأوضاع', en: 'Modes' }, { ar: 'متعددة', en: 'Multiple' }],
      [{ ar: 'التشطيب', en: 'Finish' }, { ar: 'ذهبي', en: 'Gold' }],
      [yrs, y5],
    ],
    finishes: ['gold'], images: { gold: '/products/shower-gold.webp' },
  },
  {
    id: 'tall', collection: 'mixers',
    title: { ar: 'صنبور المطبخ العالي', en: 'Tall Kitchen Faucet' },
    tagline: { ar: 'قوس مرتفع يمنح حرية كاملة حول الحوض', en: 'A high arc for full freedom around the sink' },
    desc: { ar: 'قوس مرتفع أنيق يمنح حرية حركة كاملة حول الحوض، بتصميم نحتي يتصدّر المشهد.', en: 'An elegant high arc that gives full freedom of movement around the sink, with a sculptural design that leads the scene.' },
    specs: [
      [{ ar: 'الارتفاع', en: 'Height' }, { ar: '42 سم', en: '42 cm' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [{ ar: 'التشطيب', en: 'Finish' }, { ar: 'أسود مطفي', en: 'Matte black' }],
      [yrs, y5],
    ],
    finishes: ['black'], images: { black: '/products/faucet-tall-black.webp' },
  },
  {
    id: 'bath', collection: 'bath',
    title: { ar: 'مخلط البانيو الجداري', en: 'Wall-mounted Bath Mixer' },
    tagline: { ar: 'تركيب جداري بمخرج مزدوج ومحوّل انسيابي', en: 'Wall-mounted with a dual outlet and smooth diverter' },
    desc: { ar: 'تركيب جداري بمخرج مزدوج ومحوّل انسيابي، يجمع بين قوة الأداء ونعومة التصميم.', en: 'Wall-mounted with a dual outlet and a smooth diverter, combining strong performance with a gentle design.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'المخرج', en: 'Outlet' }, { ar: 'مزدوج', en: 'Dual' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سبيكة مقاومة', en: 'Resistant alloy' }],
      [yrs, y5],
    ],
    finishes: ['black'], images: { black: '/products/faucet-bath-black.webp' },
  },
  {
    id: 'jacuzzi', collection: 'jacuzzi',
    title: { ar: 'جاكوزي التدليك الحر', en: 'Freestanding Massage Jacuzzi' },
    tagline: { ar: 'نفّاثات تدليك ومخلط جانبي بمرش يدوي', en: 'Massage jets with a side mixer and handheld spray' },
    desc: { ar: 'حوض جاكوزي حر بنفّاثات تدليك مائية ومخلط جانبي مع مرش يدوي، لتجربة استرخاء تشبه المنتجعات في منزلك.', en: 'A freestanding jacuzzi with water massage jets and a side mixer with a handheld spray — a resort-like relaxation experience at home.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'حر قائم', en: 'Freestanding' }],
      [{ ar: 'النفّاثات', en: 'Jets' }, { ar: 'تدليك مائي', en: 'Water massage' }],
      [{ ar: 'الملحقات', en: 'Extras' }, { ar: 'مرش يدوي', en: 'Handheld spray' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/jacuzzi-white.webp' },
  },
  // منتجات كتالوج Y93 (مورّد) — 34 منتجاً موزّعة على 3 طرازات، كل شكل بجميع تشطيباته المتوفرة
  {
    id: 'y93-221-a', collection: 'mixers',
    title: { ar: 'خلاط مغسلة كلاسيكي', en: 'Classic Basin Mixer' },
    tagline: { ar: 'مخرج انسيابي ومقبض جانبي مريح لأي مغسلة', en: 'A flowing spout and a comfortable side lever for any washbasin' },
    desc: { ar: 'خلاط مغسلة بتصميم كلاسيكي، مخرج انسيابي ومقبض واحد للتحكّم الدقيق بالتدفّق والحرارة.', en: 'A single-lever basin mixer with a classic design and a flowing spout for precise flow and temperature control.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مغسلة (حفرة واحدة)', en: 'Basin (single hole)' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'gray', 'black'], images: { chrome: '/products/y93-221-a-ch.webp', gray: '/products/y93-221-a-gr.webp', black: '/products/y93-221-a-bk.webp' },
  },
  {
    id: 'y93-221-b', collection: 'bath',
    title: { ar: 'مخلط بانيو جداري كلاسيكي', en: 'Classic Wall Bath Mixer' },
    tagline: { ar: 'تركيب جداري مع منفذ للمرش اليدوي', en: 'Wall-mounted with a handheld-spray outlet' },
    desc: { ar: 'مخلط بانيو جداري بتصميم كلاسيكي، مخرج بانيو ومنفذ إضافي لتوصيل مرش يدوي.', en: 'A wall-mounted bath mixer with a classic design, a tub spout and an extra port for a handheld spray.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'المنفذ', en: 'Outlet' }, { ar: 'بانيو + مرش يدوي', en: 'Tub + handheld' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'gray', 'black'], images: { chrome: '/products/y93-221-b-ch.webp', gray: '/products/y93-221-b-gr.webp', black: '/products/y93-221-b-bk.webp' },
  },
  {
    id: 'y93-221-d', collection: 'mixers',
    title: { ar: 'صنبور مطبخ عالي كلاسيكي', en: 'Classic Tall Kitchen Faucet' },
    tagline: { ar: 'قوس مرتفع يمنح حرية كاملة حول الحوض', en: 'A high arc for full freedom around the sink' },
    desc: { ar: 'صنبور مطبخ بقوس مرتفع وتصميم كلاسيكي، يمنح حرية حركة كاملة حول حوض المطبخ.', en: 'A kitchen faucet with a high arc and a classic design, giving full freedom of movement around the sink.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مطبخ', en: 'Kitchen sink' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'gray', 'black'], images: { chrome: '/products/y93-221-d-ch.webp', gray: '/products/y93-221-d-gr.webp', black: '/products/y93-221-d-bk.webp' },
  },
  {
    id: 'y93-221-g', collection: 'sprays',
    title: { ar: 'مخلط دش جداري كلاسيكي', en: 'Classic Wall Shower Valve' },
    tagline: { ar: 'تركيب جداري مباشر لتغذية الدش', en: 'Direct wall mount for a shower feed' },
    desc: { ar: 'مخلط دش جداري بسيط بتصميم كلاسيكي، مقبض واحد للتحكّم بالتدفّق والحرارة.', en: 'A simple wall-mounted shower valve with a classic design and a single lever for flow and temperature control.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مفردة (دش)', en: 'Single (shower)' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'gray', 'black'], images: { chrome: '/products/y93-221-g-ch.webp', gray: '/products/y93-221-g-gr.webp', black: '/products/y93-221-g-bk.webp' },
  },
  {
    id: 'y93-436-a', collection: 'mixers',
    title: { ar: 'خلاط مغسلة مربّع الشكل', en: 'Square-cut Basin Mixer' },
    tagline: { ar: 'مخرج انسيابي ومقبض جانبي مريح لأي مغسلة', en: 'A flowing spout and a comfortable side lever for any washbasin' },
    desc: { ar: 'خلاط مغسلة بتصميم مربّع الشكل، مخرج انسيابي ومقبض واحد للتحكّم الدقيق بالتدفّق والحرارة.', en: 'A single-lever basin mixer with a square-cut design and a flowing spout for precise flow and temperature control.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مغسلة (حفرة واحدة)', en: 'Basin (single hole)' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-a-ch.webp', rosegold: '/products/y93-436-a-rg.webp', gold: '/products/y93-436-a-tg.webp', gray: '/products/y93-436-a-gr.webp', black: '/products/y93-436-a-bk.webp' },
  },
  {
    id: 'y93-436-a1', collection: 'mixers',
    title: { ar: 'خلاط مغسلة عالي مربّع الشكل', en: 'Square-cut Tall Basin Mixer' },
    tagline: { ar: 'جسم مرتفع يناسب أحواض المغسلة الوعائية', en: 'A tall body suited to vessel-style basins' },
    desc: { ar: 'خلاط مغسلة بجسم مرتفع وتصميم مربّع الشكل، مثالي لأحواض المغسلة الوعائية (Vessel).', en: 'A basin mixer with a tall body and square-cut design, ideal for vessel-style basins.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد عالي', en: 'Tall single lever' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مغسلة وعائية', en: 'Vessel basin' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-a1-ch.webp', rosegold: '/products/y93-436-a1-rg.webp', gold: '/products/y93-436-a1-tg.webp', gray: '/products/y93-436-a1-gr.webp', black: '/products/y93-436-a1-bk.webp' },
  },
  {
    id: 'y93-436-a2', collection: 'mixers',
    title: { ar: 'خلاط مغسلة جداري مدمج مربّع الشكل', en: 'Square-cut Concealed Basin Mixer' },
    tagline: { ar: 'تركيب جداري مدمج بمخرج بارز أنيق', en: 'Wall-concealed installation with a sleek visible spout' },
    desc: { ar: 'خلاط مغسلة بتركيب جداري مدمج (الصمام داخل الحائط) بتصميم مربّع الشكل، يمنح المغسلة مظهراً نظيفاً وعصرياً.', en: 'A basin mixer with a concealed in-wall valve and a square-cut design, giving the basin a clean, modern look.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري مدمج', en: 'Wall-concealed' }],
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-a2-ch.webp', rosegold: '/products/y93-436-a2-rg.webp', gold: '/products/y93-436-a2-tg.webp', gray: '/products/y93-436-a2-gr.webp', black: '/products/y93-436-a2-bk.webp' },
  },
  {
    id: 'y93-436-a3', collection: 'mixers',
    title: { ar: 'طقم مغسلة جداري مدمج مربّع الشكل', en: 'Square-cut Concealed Widespread Basin Set' },
    tagline: { ar: 'مقبضان منفصلان جداريان مع مخرج مدمج مربّع الشكل', en: 'Separate wall-mounted handles with a square-cut concealed spout' },
    desc: { ar: 'طقم مغسلة بتركيب جداري مدمج (الصمام داخل الحائط) ومقبضين منفصلين للحرارة والتدفّق، بتصميم مربّع الشكل يمنح المغسلة مظهراً نظيفاً وعصرياً.', en: 'A basin set with a concealed in-wall valve and separate hot/cold handles, in a square-cut design that gives the basin a clean, modern look.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري مدمج', en: 'Wall-concealed' }],
      [{ ar: 'النوع', en: 'Type' }, { ar: 'مقبضان منفصلان', en: 'Separate two-handle' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-436-a3-ch.webp', rosegold: '/products/y93-436-a3-rg.webp', gold: '/products/y93-436-a3-tg.webp', black: '/products/y93-436-a3-bk.webp' },
  },
  {
    id: 'y93-436-a4', collection: 'mixers',
    title: { ar: 'طقم مغسلة ثلاثي مربّع الشكل', en: 'Square-cut Widespread Basin Set' },
    tagline: { ar: 'مقبضان منفصلان للحرارة والتدفّق مع مخرج مقوّس', en: 'Separate hot/cold handles with a curved centre spout' },
    desc: { ar: 'طقم مغسلة ثلاثي الفتحات (Widespread) بتصميم مربّع الشكل، مقبضان منفصلان ومخرج مقوّس أنيق.', en: 'A 3-hole widespread basin set with a square-cut design — separate handles and an elegant arched spout.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'ثلاثي الفتحات', en: '3-hole widespread' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مغسلة', en: 'Deck-mounted' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-436-a4-ch.webp', rosegold: '/products/y93-436-a4-rg.webp', gold: '/products/y93-436-a4-tg.webp', black: '/products/y93-436-a4-bk.webp' },
  },
  {
    id: 'y93-436-a5', collection: 'mixers',
    title: { ar: 'خلاط مغسلة سنسور مربّع الشكل', en: 'Square-cut Sensor Basin Faucet' },
    tagline: { ar: 'تشغيل تلقائي بالاستشعار دون لمس', en: 'Touch-free automatic sensor operation' },
    desc: { ar: 'خلاط مغسلة تلقائي يعمل بحساس حركة دون لمس، بتصميم مربّع الشكل يناسب المساحات العامة والمنزلية.', en: 'A touch-free sensor basin faucet with a square-cut design, suited to both home and public bathrooms.' },
    specs: [
      [{ ar: 'التشغيل', en: 'Operation' }, { ar: 'حساس تلقائي', en: 'Automatic sensor' }],
      [{ ar: 'الطاقة', en: 'Power' }, { ar: 'بطارية / كهربائي', en: 'Battery / AC' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-436-a5-ch.webp', rosegold: '/products/y93-436-a5-rg.webp', gold: '/products/y93-436-a5-tg.webp', black: '/products/y93-436-a5-bk.webp' },
  },
  {
    id: 'y93-436-b', collection: 'bath',
    title: { ar: 'مخلط بانيو جداري مربّع الشكل', en: 'Square-cut Wall Bath Mixer' },
    tagline: { ar: 'تركيب جداري مع منفذ للمرش اليدوي', en: 'Wall-mounted with a handheld-spray outlet' },
    desc: { ar: 'مخلط بانيو جداري بتصميم مربّع الشكل، مخرج بانيو ومنفذ إضافي لتوصيل مرش يدوي.', en: 'A wall-mounted bath mixer with a square-cut design, a tub spout and an extra port for a handheld spray.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'المنفذ', en: 'Outlet' }, { ar: 'بانيو + مرش يدوي', en: 'Tub + handheld' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-b-ch.webp', rosegold: '/products/y93-436-b-rg.webp', gold: '/products/y93-436-b-tg.webp', gray: '/products/y93-436-b-gr.webp', black: '/products/y93-436-b-bk.webp' },
  },
  {
    id: 'y93-436-b1', collection: 'sprays',
    title: { ar: 'مخلط دش مدمج مربّع الشكل', en: 'Square-cut Concealed Shower Mixer' },
    tagline: { ar: 'صمام مدمج بالحائط بمقبض واحد للتحكّم', en: 'Wall-concealed valve with a single control lever' },
    desc: { ar: 'مخلط دش مدمج داخل الحائط بمقبض واحد بتصميم مربّع الشكل، يظهر منه فقط اللوحة والمقبض.', en: 'A concealed in-wall shower valve with a single lever, square-cut design — only the plate and handle stay visible.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري مدمج', en: 'Wall-concealed' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مفردة', en: 'Single function' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-b1-ch.webp', rosegold: '/products/y93-436-b1-rg.webp', gold: '/products/y93-436-b1-tg.webp', gray: '/products/y93-436-b1-gr.webp', black: '/products/y93-436-b1-bk.webp' },
  },
  {
    id: 'y93-436-b2', collection: 'bath',
    title: { ar: 'مخلط بانيو مدمج مربّع الشكل', en: 'Square-cut Concealed Bath Mixer' },
    tagline: { ar: 'صمام مدمج بمحوّل لتبديل المخرج', en: 'Concealed valve with a diverter to switch outlets' },
    desc: { ar: 'مخلط جداري مدمج بمحوّل (Diverter) للتبديل بين مخرجين، بتصميم مربّع الشكل أنيق يظهر منه فقط اللوحة.', en: 'A concealed wall valve with a diverter to switch between two outlets, in a square-cut design — only the plate stays visible.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري مدمج', en: 'Wall-concealed' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مزدوجة بمحوّل', en: 'Dual, with diverter' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-b2-ch.webp', rosegold: '/products/y93-436-b2-rg.webp', gold: '/products/y93-436-b2-tg.webp', gray: '/products/y93-436-b2-gr.webp', black: '/products/y93-436-b2-bk.webp' },
  },
  {
    id: 'y93-436-b4', collection: 'bath',
    title: { ar: 'صنبور بانيو حر مربّع الشكل', en: 'Square-cut Freestanding Bath Filler' },
    tagline: { ar: 'صنبور أرضي حر مع مرش يدوي', en: 'A floor-standing filler with a handheld spray' },
    desc: { ar: 'صنبور بانيو حر قائم على الأرض بتصميم مربّع الشكل، مزوّد بمرش يدوي بخرطوم مرن لتجربة استحمام مريحة.', en: 'A floor-standing freestanding bath filler with a square-cut design and a flexible-hose handheld spray for a comfortable bathing experience.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'حر قائم (أرضي)', en: 'Freestanding (floor)' }],
      [{ ar: 'الملحقات', en: 'Extras' }, { ar: 'مرش يدوي', en: 'Handheld spray' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-436-b4-ch.webp', rosegold: '/products/y93-436-b4-rg.webp', gold: '/products/y93-436-b4-tg.webp', black: '/products/y93-436-b4-bk.webp' },
  },
  {
    id: 'y93-436-b5', collection: 'bath',
    title: { ar: 'صنبور بانيو حر مربّع الشكل — طراز آخر', en: 'Square-cut Freestanding Bath Filler — Alt' },
    tagline: { ar: 'صنبور أرضي حر بمخرج مرتفع ومرش يدوي', en: 'A floor-standing filler with a raised spout and handheld spray' },
    desc: { ar: 'صنبور بانيو حر بمخرج مرتفع وتصميم مربّع الشكل، مزوّد بمرش يدوي بخرطوم مرن.', en: 'A freestanding bath filler with a raised spout and a square-cut design, fitted with a flexible-hose handheld spray.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'حر قائم (أرضي)', en: 'Freestanding (floor)' }],
      [{ ar: 'الملحقات', en: 'Extras' }, { ar: 'مرش يدوي', en: 'Handheld spray' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-436-b5-ch.webp', rosegold: '/products/y93-436-b5-rg.webp', gold: '/products/y93-436-b5-tg.webp', black: '/products/y93-436-b5-bk.webp' },
  },
  {
    id: 'y93-436-b6', collection: 'sprays',
    title: { ar: 'نظام دش متكامل مربّع الشكل', en: 'Square-cut Complete Shower System' },
    tagline: { ar: 'مرش علوي مطري ويدوي وصمام جداري', en: 'Overhead rain head, handheld spray, and wall valve' },
    desc: { ar: 'نظام دش متكامل بمرش علوي عريض ورأس يدوي وصمام جداري بتصميم مربّع الشكل، لتجربة استحمام فندقية.', en: 'A complete shower system with a wide overhead rain head, a handheld spray, and a wall valve in a square-cut design — a hotel-style shower experience.' },
    specs: [
      [{ ar: 'المرش', en: 'Heads' }, { ar: 'علوي + يدوي', en: 'Overhead + handheld' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مفردة', en: 'Single function' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-b6-ch.webp', rosegold: '/products/y93-436-b6-rg.webp', gold: '/products/y93-436-b6-tg.webp', gray: '/products/y93-436-b6-gr.webp', black: '/products/y93-436-b6-bk.webp' },
  },
  {
    id: 'y93-436-d', collection: 'mixers',
    title: { ar: 'صنبور مطبخ عالي مربّع الشكل', en: 'Square-cut Tall Kitchen Faucet' },
    tagline: { ar: 'قوس مرتفع يمنح حرية كاملة حول الحوض', en: 'A high arc for full freedom around the sink' },
    desc: { ar: 'صنبور مطبخ بقوس مرتفع وتصميم مربّع الشكل، يمنح حرية حركة كاملة حول حوض المطبخ.', en: 'A kitchen faucet with a high arc and a square-cut design, giving full freedom of movement around the sink.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مطبخ', en: 'Kitchen sink' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-d-ch.webp', rosegold: '/products/y93-436-d-rg.webp', gold: '/products/y93-436-d-tg.webp', gray: '/products/y93-436-d-gr.webp', black: '/products/y93-436-d-bk.webp' },
  },
  {
    id: 'y93-436-e', collection: 'mixers',
    title: { ar: 'صنبور مطبخ بمرش سحب مربّع الشكل', en: 'Square-cut Pull-down Kitchen Faucet' },
    tagline: { ar: 'رأس سحب متعدد الأوضاع لتنظيف أسهل', en: 'A multi-mode pull-down head for easier cleaning' },
    desc: { ar: 'صنبور مطبخ برأس سحب مرن متعدد أوضاع الرش، بتصميم مربّع الشكل يسهّل مهام المطبخ اليومية.', en: 'A kitchen faucet with a flexible, multi-mode pull-down spray head, in a square-cut design that eases daily kitchen tasks.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'مرش سحب مرن', en: 'Pull-down spray' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مطبخ', en: 'Kitchen sink' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-e-ch.webp', rosegold: '/products/y93-436-e-rg.webp', gold: '/products/y93-436-e-tg.webp', gray: '/products/y93-436-e-gr.webp', black: '/products/y93-436-e-bk.webp' },
  },
  {
    id: 'y93-436-f', collection: 'mixers',
    title: { ar: 'مخلط جداري طويل المخرج مربّع الشكل', en: 'Square-cut Long-spout Wall Mixer' },
    tagline: { ar: 'تركيب جداري بمخرج طويل يناسب المطبخ والمغسلة', en: 'Wall-mounted with a long spout for kitchen or basin' },
    desc: { ar: 'مخلط جداري بمخرج طويل انسيابي وتصميم مربّع الشكل، يناسب أحواض المطبخ والمغاسل العميقة.', en: 'A wall-mounted mixer with a long flowing spout and a square-cut design, suited to kitchen sinks and deep basins.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'المخرج', en: 'Spout' }, { ar: 'طويل انسيابي', en: 'Long, flowing' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-f-ch.webp', rosegold: '/products/y93-436-f-rg.webp', gold: '/products/y93-436-f-tg.webp', gray: '/products/y93-436-f-gr.webp', black: '/products/y93-436-f-bk.webp' },
  },
  {
    id: 'y93-436-g', collection: 'sprays',
    title: { ar: 'مخلط دش جداري مربّع الشكل', en: 'Square-cut Wall Shower Valve' },
    tagline: { ar: 'تركيب جداري مباشر لتغذية الدش', en: 'Direct wall mount for a shower feed' },
    desc: { ar: 'مخلط دش جداري بسيط بتصميم مربّع الشكل، مقبض واحد للتحكّم بالتدفّق والحرارة.', en: 'A simple wall-mounted shower valve with a square-cut design and a single lever for flow and temperature control.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مفردة (دش)', en: 'Single (shower)' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'gray', 'black'], images: { chrome: '/products/y93-436-g-ch.webp', rosegold: '/products/y93-436-g-rg.webp', gold: '/products/y93-436-g-tg.webp', gray: '/products/y93-436-g-gr.webp', black: '/products/y93-436-g-bk.webp' },
  },
  {
    id: 'y93-572-a', collection: 'mixers',
    title: { ar: 'خلاط مغسلة انسيابي', en: 'Streamlined Basin Mixer' },
    tagline: { ar: 'مخرج انسيابي ومقبض جانبي مريح لأي مغسلة', en: 'A flowing spout and a comfortable side lever for any washbasin' },
    desc: { ar: 'خلاط مغسلة بتصميم انسيابي، مخرج انسيابي ومقبض واحد للتحكّم الدقيق بالتدفّق والحرارة.', en: 'A single-lever basin mixer with a streamlined design and a flowing spout for precise flow and temperature control.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مغسلة (حفرة واحدة)', en: 'Basin (single hole)' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-a-ch.webp', rosegold: '/products/y93-572-a-rg.webp', gold: '/products/y93-572-a-tg.webp', black: '/products/y93-572-a-bk.webp' },
  },
  {
    id: 'y93-572-a1', collection: 'mixers',
    title: { ar: 'خلاط مغسلة عالي انسيابي', en: 'Streamlined Tall Basin Mixer' },
    tagline: { ar: 'جسم مرتفع يناسب أحواض المغسلة الوعائية', en: 'A tall body suited to vessel-style basins' },
    desc: { ar: 'خلاط مغسلة بجسم مرتفع وتصميم انسيابي، مثالي لأحواض المغسلة الوعائية (Vessel).', en: 'A basin mixer with a tall body and streamlined design, ideal for vessel-style basins.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد عالي', en: 'Tall single lever' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مغسلة وعائية', en: 'Vessel basin' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-a1-ch.webp', rosegold: '/products/y93-572-a1-rg.webp', gold: '/products/y93-572-a1-tg.webp', black: '/products/y93-572-a1-bk.webp' },
  },
  {
    id: 'y93-572-a2', collection: 'mixers',
    title: { ar: 'خلاط مغسلة جداري مدمج انسيابي', en: 'Streamlined Concealed Basin Mixer' },
    tagline: { ar: 'تركيب جداري مدمج بمخرج بارز أنيق', en: 'Wall-concealed installation with a sleek visible spout' },
    desc: { ar: 'خلاط مغسلة بتركيب جداري مدمج (الصمام داخل الحائط) بتصميم انسيابي، يمنح المغسلة مظهراً نظيفاً وعصرياً.', en: 'A basin mixer with a concealed in-wall valve and a streamlined design, giving the basin a clean, modern look.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري مدمج', en: 'Wall-concealed' }],
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-a2-ch.webp', rosegold: '/products/y93-572-a2-rg.webp', gold: '/products/y93-572-a2-tg.webp', black: '/products/y93-572-a2-bk.webp' },
  },
  {
    id: 'y93-572-a3', collection: 'mixers',
    title: { ar: 'طقم مغسلة جداري مدمج انسيابي', en: 'Streamlined Concealed Widespread Basin Set' },
    tagline: { ar: 'مقبضان منفصلان جداريان مع مخرج مدمج انسيابي', en: 'Separate wall-mounted handles with a streamlined concealed spout' },
    desc: { ar: 'طقم مغسلة بتركيب جداري مدمج (الصمام داخل الحائط) ومقبضين منفصلين للحرارة والتدفّق، بتصميم انسيابي يمنح المغسلة مظهراً نظيفاً وعصرياً.', en: 'A basin set with a concealed in-wall valve and separate hot/cold handles, in a streamlined design that gives the basin a clean, modern look.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري مدمج', en: 'Wall-concealed' }],
      [{ ar: 'النوع', en: 'Type' }, { ar: 'مقبضان منفصلان', en: 'Separate two-handle' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-a3-ch.webp', rosegold: '/products/y93-572-a3-rg.webp', gold: '/products/y93-572-a3-tg.webp', black: '/products/y93-572-a3-bk.webp' },
  },
  {
    id: 'y93-572-a5', collection: 'mixers',
    title: { ar: 'خلاط مغسلة سنسور انسيابي', en: 'Streamlined Sensor Basin Faucet' },
    tagline: { ar: 'تشغيل تلقائي بالاستشعار دون لمس', en: 'Touch-free automatic sensor operation' },
    desc: { ar: 'خلاط مغسلة تلقائي يعمل بحساس حركة دون لمس، بتصميم انسيابي يناسب المساحات العامة والمنزلية.', en: 'A touch-free sensor basin faucet with a streamlined design, suited to both home and public bathrooms.' },
    specs: [
      [{ ar: 'التشغيل', en: 'Operation' }, { ar: 'حساس تلقائي', en: 'Automatic sensor' }],
      [{ ar: 'الطاقة', en: 'Power' }, { ar: 'بطارية / كهربائي', en: 'Battery / AC' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-a5-ch.webp', rosegold: '/products/y93-572-a5-rg.webp', gold: '/products/y93-572-a5-tg.webp', black: '/products/y93-572-a5-bk.webp' },
  },
  {
    id: 'y93-572-b', collection: 'bath',
    title: { ar: 'مخلط بانيو جداري انسيابي', en: 'Streamlined Wall Bath Mixer' },
    tagline: { ar: 'تركيب جداري مع منفذ للمرش اليدوي', en: 'Wall-mounted with a handheld-spray outlet' },
    desc: { ar: 'مخلط بانيو جداري بتصميم انسيابي، مخرج بانيو ومنفذ إضافي لتوصيل مرش يدوي.', en: 'A wall-mounted bath mixer with a streamlined design, a tub spout and an extra port for a handheld spray.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'المنفذ', en: 'Outlet' }, { ar: 'بانيو + مرش يدوي', en: 'Tub + handheld' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-b-ch.webp', rosegold: '/products/y93-572-b-rg.webp', gold: '/products/y93-572-b-tg.webp', black: '/products/y93-572-b-bk.webp' },
  },
  {
    id: 'y93-572-b1', collection: 'sprays',
    title: { ar: 'مخلط دش مدمج انسيابي', en: 'Streamlined Concealed Shower Mixer' },
    tagline: { ar: 'صمام مدمج بالحائط بمقبض واحد للتحكّم', en: 'Wall-concealed valve with a single control lever' },
    desc: { ar: 'مخلط دش مدمج داخل الحائط بمقبض واحد بتصميم انسيابي، يظهر منه فقط اللوحة والمقبض.', en: 'A concealed in-wall shower valve with a single lever, streamlined design — only the plate and handle stay visible.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري مدمج', en: 'Wall-concealed' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مفردة', en: 'Single function' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-b1-ch.webp', rosegold: '/products/y93-572-b1-rg.webp', gold: '/products/y93-572-b1-tg.webp', black: '/products/y93-572-b1-bk.webp' },
  },
  {
    id: 'y93-572-b2', collection: 'bath',
    title: { ar: 'مخلط بانيو مدمج انسيابي', en: 'Streamlined Concealed Bath Mixer' },
    tagline: { ar: 'صمام مدمج بمحوّل لتبديل المخرج', en: 'Concealed valve with a diverter to switch outlets' },
    desc: { ar: 'مخلط جداري مدمج بمحوّل (Diverter) للتبديل بين مخرجين، بتصميم انسيابي أنيق يظهر منه فقط اللوحة.', en: 'A concealed wall valve with a diverter to switch between two outlets, in a streamlined design — only the plate stays visible.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري مدمج', en: 'Wall-concealed' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مزدوجة بمحوّل', en: 'Dual, with diverter' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-b2-ch.webp', rosegold: '/products/y93-572-b2-rg.webp', gold: '/products/y93-572-b2-tg.webp', black: '/products/y93-572-b2-bk.webp' },
  },
  {
    id: 'y93-572-b4', collection: 'bath',
    title: { ar: 'صنبور بانيو حر انسيابي', en: 'Streamlined Freestanding Bath Filler' },
    tagline: { ar: 'صنبور أرضي حر مع مرش يدوي', en: 'A floor-standing filler with a handheld spray' },
    desc: { ar: 'صنبور بانيو حر قائم على الأرض بتصميم انسيابي، مزوّد بمرش يدوي بخرطوم مرن لتجربة استحمام مريحة.', en: 'A floor-standing freestanding bath filler with a streamlined design and a flexible-hose handheld spray for a comfortable bathing experience.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'حر قائم (أرضي)', en: 'Freestanding (floor)' }],
      [{ ar: 'الملحقات', en: 'Extras' }, { ar: 'مرش يدوي', en: 'Handheld spray' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-b4-ch.webp', rosegold: '/products/y93-572-b4-rg.webp', gold: '/products/y93-572-b4-tg.webp', black: '/products/y93-572-b4-bk.webp' },
  },
  {
    id: 'y93-572-b5', collection: 'bath',
    title: { ar: 'صنبور بانيو حر انسيابي — طراز آخر', en: 'Streamlined Freestanding Bath Filler — Alt' },
    tagline: { ar: 'صنبور أرضي حر بمخرج مرتفع ومرش يدوي', en: 'A floor-standing filler with a raised spout and handheld spray' },
    desc: { ar: 'صنبور بانيو حر بمخرج مرتفع وتصميم انسيابي، مزوّد بمرش يدوي بخرطوم مرن.', en: 'A freestanding bath filler with a raised spout and a streamlined design, fitted with a flexible-hose handheld spray.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'حر قائم (أرضي)', en: 'Freestanding (floor)' }],
      [{ ar: 'الملحقات', en: 'Extras' }, { ar: 'مرش يدوي', en: 'Handheld spray' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-b5-ch.webp', rosegold: '/products/y93-572-b5-rg.webp', gold: '/products/y93-572-b5-tg.webp', black: '/products/y93-572-b5-bk.webp' },
  },
  {
    id: 'y93-572-b6', collection: 'sprays',
    title: { ar: 'نظام دش متكامل انسيابي', en: 'Streamlined Complete Shower System' },
    tagline: { ar: 'مرش علوي مطري ويدوي وصمام جداري', en: 'Overhead rain head, handheld spray, and wall valve' },
    desc: { ar: 'نظام دش متكامل بمرش علوي عريض ورأس يدوي وصمام جداري بتصميم انسيابي، لتجربة استحمام فندقية.', en: 'A complete shower system with a wide overhead rain head, a handheld spray, and a wall valve in a streamlined design — a hotel-style shower experience.' },
    specs: [
      [{ ar: 'المرش', en: 'Heads' }, { ar: 'علوي + يدوي', en: 'Overhead + handheld' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مفردة', en: 'Single function' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-b6-ch.webp', rosegold: '/products/y93-572-b6-rg.webp', gold: '/products/y93-572-b6-tg.webp', black: '/products/y93-572-b6-bk.webp' },
  },
  {
    id: 'y93-572-d', collection: 'mixers',
    title: { ar: 'صنبور مطبخ عالي انسيابي', en: 'Streamlined Tall Kitchen Faucet' },
    tagline: { ar: 'قوس مرتفع يمنح حرية كاملة حول الحوض', en: 'A high arc for full freedom around the sink' },
    desc: { ar: 'صنبور مطبخ بقوس مرتفع وتصميم انسيابي، يمنح حرية حركة كاملة حول حوض المطبخ.', en: 'A kitchen faucet with a high arc and a streamlined design, giving full freedom of movement around the sink.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'خلاط مفرد', en: 'Single lever' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مطبخ', en: 'Kitchen sink' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-d-ch.webp', rosegold: '/products/y93-572-d-rg.webp', gold: '/products/y93-572-d-tg.webp', black: '/products/y93-572-d-bk.webp' },
  },
  {
    id: 'y93-572-e', collection: 'mixers',
    title: { ar: 'صنبور مطبخ بمرش سحب انسيابي', en: 'Streamlined Pull-down Kitchen Faucet' },
    tagline: { ar: 'رأس سحب متعدد الأوضاع لتنظيف أسهل', en: 'A multi-mode pull-down head for easier cleaning' },
    desc: { ar: 'صنبور مطبخ برأس سحب مرن متعدد أوضاع الرش، بتصميم انسيابي يسهّل مهام المطبخ اليومية.', en: 'A kitchen faucet with a flexible, multi-mode pull-down spray head, in a streamlined design that eases daily kitchen tasks.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'مرش سحب مرن', en: 'Pull-down spray' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مطبخ', en: 'Kitchen sink' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'black'], images: { chrome: '/products/y93-572-e-ch.webp', rosegold: '/products/y93-572-e-rg.webp', black: '/products/y93-572-e-bk.webp' },
  },
  {
    id: 'y93-572-f', collection: 'mixers',
    title: { ar: 'مخلط جداري طويل المخرج انسيابي', en: 'Streamlined Long-spout Wall Mixer' },
    tagline: { ar: 'تركيب جداري بمخرج طويل يناسب المطبخ والمغسلة', en: 'Wall-mounted with a long spout for kitchen or basin' },
    desc: { ar: 'مخلط جداري بمخرج طويل انسيابي وتصميم انسيابي، يناسب أحواض المطبخ والمغاسل العميقة.', en: 'A wall-mounted mixer with a long flowing spout and a streamlined design, suited to kitchen sinks and deep basins.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'المخرج', en: 'Spout' }, { ar: 'طويل انسيابي', en: 'Long, flowing' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-f-ch.webp', rosegold: '/products/y93-572-f-rg.webp', gold: '/products/y93-572-f-tg.webp', black: '/products/y93-572-f-bk.webp' },
  },
  {
    id: 'y93-572-g', collection: 'sprays',
    title: { ar: 'مخلط دش جداري انسيابي', en: 'Streamlined Wall Shower Valve' },
    tagline: { ar: 'تركيب جداري مباشر لتغذية الدش', en: 'Direct wall mount for a shower feed' },
    desc: { ar: 'مخلط دش جداري بسيط بتصميم انسيابي، مقبض واحد للتحكّم بالتدفّق والحرارة.', en: 'A simple wall-mounted shower valve with a streamlined design and a single lever for flow and temperature control.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'الوظيفة', en: 'Function' }, { ar: 'مفردة (دش)', en: 'Single (shower)' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'rosegold', 'gold', 'black'], images: { chrome: '/products/y93-572-g-ch.webp', rosegold: '/products/y93-572-g-rg.webp', gold: '/products/y93-572-g-tg.webp', black: '/products/y93-572-g-bk.webp' },
  },
  {
    id: 'y93-572-a4', collection: 'mixers',
    title: { ar: 'طقم مغسلة ثلاثي انسيابي', en: 'Streamlined Widespread Basin Set' },
    tagline: { ar: 'مقبضان منفصلان للحرارة والتدفّق مع مخرج مقوّس', en: 'Separate hot/cold handles with a curved centre spout' },
    desc: { ar: 'طقم مغسلة ثلاثي الفتحات (Widespread) بتصميم انسيابي، مقبضان منفصلان ومخرج مقوّس أنيق.', en: 'A 3-hole widespread basin set with a streamlined design — separate handles and an elegant arched spout.' },
    specs: [
      [{ ar: 'النوع', en: 'Type' }, { ar: 'ثلاثي الفتحات', en: '3-hole widespread' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'مغسلة', en: 'Deck-mounted' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['rosegold', 'gold', 'black'], images: { rosegold: '/products/y93-572-a4-rg.webp', gold: '/products/y93-572-a4-tg.webp', black: '/products/y93-572-a4-bk.webp' },
  },
  // ملحقات وتركيبات (كتالوج N05) — محابس زاوية
  {
    id: 'valve-corner-ar', collection: 'accessories',
    title: { ar: 'محبس زاوية كلاسيكي', en: 'Classic Angle Valve' },
    tagline: { ar: 'محبس تغذية زاوية بتصميم أنيق لتوصيل خطوط المياه', en: 'An elegant angle-stop valve for water supply connections' },
    desc: { ar: 'محبس زاوية 1/2×1/2 بتشطيب كروم لامع، يُستخدم للتحكّم في تغذية المياه لأدوات الحمّام والمطبخ بسهولة وأمان.', en: 'A 1/2×1/2 angle stop valve in a polished chrome finish, used to control the water supply to bathroom and kitchen fixtures safely and easily.' },
    specs: [
      [{ ar: 'المقاس', en: 'Size' }, { ar: '1/2 × 1/2 بوصة', en: '1/2 × 1/2 inch' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome'], images: { chrome: '/products/valve-corner-ar-ch.webp' },
  },
  {
    id: 'valve-corner-gr', collection: 'accessories',
    title: { ar: 'محبس زاوية عصري', en: 'Modern Angle Valve' },
    tagline: { ar: 'محبس تغذية زاوية بمقبض هرمي عصري', en: 'An angle-stop valve with a modern pyramid handle' },
    desc: { ar: 'محبس زاوية 1/2×1/2 بمقبض هرمي عصري ومتوفر بتشطيبين، يُستخدم للتحكّم في تغذية المياه لأدوات الحمّام والمطبخ.', en: 'A 1/2×1/2 angle stop valve with a modern pyramid-shaped handle, available in two finishes, used to control the water supply to bathroom and kitchen fixtures.' },
    specs: [
      [{ ar: 'المقاس', en: 'Size' }, { ar: '1/2 × 1/2 بوصة', en: '1/2 × 1/2 inch' }],
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'جداري', en: 'Wall' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'نحاس مصقول', en: 'Polished brass' }],
      [yrs, y5],
    ],
    finishes: ['chrome', 'black'], images: { chrome: '/products/valve-corner-gr-ch.webp', black: '/products/valve-corner-gr-bk.webp' },
  },
  // صفايات أرضية إضافية — ملحقات وتركيبات
  {
    id: 'drain-tile-rect', collection: 'accessories',
    title: { ar: 'صفاية أرضية مستطيلة مدمجة بالبلاط', en: 'Rectangular Tile-Insert Floor Drain' },
    tagline: { ar: 'صفاية مستطيلة بإطار عميق يخفي حواف البلاط', en: 'A rectangular drain with a deep frame that conceals tile edges' },
    desc: { ar: 'صفاية أرضية مستطيلة بإطار عميق مصمّم لإخفاء حواف البلاط المحيطة، بتشطيب ستانلس ستيل لامع.', en: 'A rectangular floor drain with a deep frame designed to conceal the surrounding tile edges, in a polished stainless-steel finish.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي مدمج بالبلاط', en: 'Tile-insert' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'ستانلس ستيل', en: 'Stainless steel' }],
      [yrs, y5],
    ],
    finishes: ['chrome'], images: { chrome: '/products/drain-tile-rect.webp' },
  },
  {
    id: 'drain-tile-square', collection: 'accessories',
    title: { ar: 'صفاية أرضية مربّعة مدمجة بالبلاط', en: 'Square Tile-Insert Floor Drain' },
    tagline: { ar: 'صفاية مربّعة بإطار عميق يخفي حواف البلاط', en: 'A square drain with a deep frame that conceals tile edges' },
    desc: { ar: 'صفاية أرضية مربّعة بإطار عميق مصمّم لإخفاء حواف البلاط المحيطة، بتشطيب ستانلس ستيل لامع.', en: 'A square floor drain with a deep frame designed to conceal the surrounding tile edges, in a polished stainless-steel finish.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي مدمج بالبلاط', en: 'Tile-insert' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'ستانلس ستيل', en: 'Stainless steel' }],
      [yrs, y5],
    ],
    finishes: ['chrome'], images: { chrome: '/products/drain-tile-square.webp' },
  },
  {
    id: 'drain-linear-slot', collection: 'accessories',
    title: { ar: 'صفاية أرضية خطّية بشبكة مزخرفة', en: 'Linear Floor Drain — Patterned Grate' },
    tagline: { ar: 'صفاية خطّية مستطيلة بفتحات تصريف متعرّجة', en: 'A rectangular linear drain with a staggered slot pattern' },
    desc: { ar: 'صفاية خطّية مستطيلة بشبكة تصريف ذات فتحات متعرّجة، بتشطيب ستانلس ستيل لامع يناسب الأرضيات الحديثة.', en: 'A rectangular linear drain with a staggered slotted grate, in a polished stainless-steel finish suited to modern flooring.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي مدمج', en: 'Floor-flush' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'ستانلس ستيل', en: 'Stainless steel' }],
      [yrs, y5],
    ],
    finishes: ['chrome'], images: { chrome: '/products/drain-linear-slot.webp' },
  },
  {
    id: 'drain-disc-cover', collection: 'accessories',
    title: { ar: 'صفاية أرضية بغطاء دائري مزخرف', en: 'Floor Drain — Decorative Disc Cover' },
    tagline: { ar: 'صفاية مربّعة بغطاء دائري مزخرف قابل للرفع', en: 'A square drain with a removable decorative disc cover' },
    desc: { ar: 'صفاية أرضية مربّعة الشكل بغطاء دائري مزخرف قابل للرفع لتسهيل التنظيف، بتشطيب ستانلس ستيل لامع.', en: 'A square-shaped floor drain with a removable decorative disc cover for easy cleaning, in a polished stainless-steel finish.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي مدمج', en: 'Floor-flush' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'ستانلس ستيل', en: 'Stainless steel' }],
      [yrs, y5],
    ],
    finishes: ['chrome'], images: { chrome: '/products/drain-disc-cover.webp' },
  },
  {
    id: 'drain-cover-round', collection: 'accessories',
    title: { ar: 'صفاية أرضية بغطاء دائري مسطّح', en: 'Floor Drain — Flat Round Cover' },
    tagline: { ar: 'صفاية مربّعة بغطاء دائري مسطّح قابل للرفع', en: 'A square drain with a removable flat round cover' },
    desc: { ar: 'صفاية أرضية مربّعة الشكل بغطاء دائري مسطّح قابل للرفع لتسهيل الوصول والتنظيف، بتشطيب ستانلس ستيل لامع.', en: 'A square-shaped floor drain with a removable flat round cover for easy access and cleaning, in a polished stainless-steel finish.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي مدمج', en: 'Floor-flush' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'ستانلس ستيل', en: 'Stainless steel' }],
      [yrs, y5],
    ],
    finishes: ['chrome'], images: { chrome: '/products/drain-cover-round.webp' },
  },
  {
    id: 'drain-perforated-screw', collection: 'accessories',
    title: { ar: 'صفاية أرضية بشبكة مثقّبة وغطاء مبرغي', en: 'Floor Drain — Perforated Grate, Screwed Cover' },
    tagline: { ar: 'صفاية مربّعة بشبكة مثقّبة وغطاء دائري مبرغي', en: 'A square drain with a perforated grate and a screwed round cover' },
    desc: { ar: 'صفاية أرضية مربّعة الشكل بشبكة تصريف مثقّبة وغطاء دائري مبرغي، بتشطيب ستانلس ستيل لامع.', en: 'A square-shaped floor drain with a perforated drainage grate and a screwed round cover, in a polished stainless-steel finish.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي مدمج', en: 'Floor-flush' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'ستانلس ستيل', en: 'Stainless steel' }],
      [yrs, y5],
    ],
    finishes: ['chrome'], images: { chrome: '/products/drain-perforated-screw.webp' },
  },
  // مغاسل جديدة
  {
    id: 'basin-wallhung-boxy', collection: 'basins',
    title: { ar: 'مغسلة معلّقة — مربّعة الحواف', en: 'Wall-Hung Basin — Square-edge' },
    tagline: { ar: 'مغسلة معلّقة بالحائط بتصميم مربّع نظيف', en: 'A wall-hung basin with a clean square-edged design' },
    desc: { ar: 'مغسلة معلّقة بالحائط بتصميم مربّع الحواف، توفّر مساحة أسفل المغسلة وتمنح الحمّام مظهراً عصرياً.', en: 'A wall-hung basin with a square-edged design that frees up space beneath it and gives the bathroom a modern look.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'معلّق بالحائط', en: 'Wall-hung' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/basin-wallhung-boxy.webp' },
  },
  {
    id: 'basin-wallhung-rounded', collection: 'basins',
    title: { ar: 'مغسلة معلّقة — منحنية ناعمة', en: 'Wall-Hung Basin — Soft Curve' },
    tagline: { ar: 'مغسلة معلّقة بالحائط بخطوط منحنية ناعمة', en: 'A wall-hung basin with soft curved lines' },
    desc: { ar: 'مغسلة معلّقة بالحائط بخطوط منحنية ناعمة تمنح الحمّام مظهراً هادئاً وعصرياً.', en: 'A wall-hung basin with soft curved lines that give the bathroom a calm, modern look.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'معلّق بالحائط', en: 'Wall-hung' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/basin-wallhung-rounded.webp' },
  },
  {
    id: 'basin-wallhung-trumpet', collection: 'basins',
    title: { ar: 'مغسلة معلّقة — بروفايل موسّع', en: 'Wall-Hung Basin — Flared Profile' },
    tagline: { ar: 'مغسلة معلّقة بالحائط بجسم متّسع نحو القاعدة', en: 'A wall-hung basin with a body that flares toward the base' },
    desc: { ar: 'مغسلة معلّقة بالحائط بجسم متّسع نحو القاعدة يمنحها حضوراً نحتياً مميّزاً.', en: 'A wall-hung basin with a body that flares toward the base, giving it a distinctive sculptural presence.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'معلّق بالحائط', en: 'Wall-hung' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/basin-wallhung-trumpet.webp' },
  },
  {
    id: 'basin-pedestal-oval', collection: 'basins',
    title: { ar: 'مغسلة بقاعدة — بيضاوية', en: 'Pedestal Basin — Oval' },
    tagline: { ar: 'مغسلة بقاعدة أرضية بحوض بيضاوي كلاسيكي', en: 'A floor-standing pedestal basin with a classic oval bowl' },
    desc: { ar: 'مغسلة بقاعدة أرضية بحوض بيضاوي كلاسيكي، بتصميم نظيف يناسب الحمّامات بمساحاتها المختلفة.', en: 'A floor-standing pedestal basin with a classic oval bowl and a clean design, suited to bathrooms of various sizes.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'بقاعدة أرضية', en: 'Pedestal-mounted' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/basin-pedestal-oval.webp' },
  },
  // مراحيض جديدة
  {
    id: 'toilet-wallhung-boxy', collection: 'toilets',
    title: { ar: 'كرسي حمام معلّق — مربّع الحواف', en: 'Wall-Hung Toilet — Square-edge' },
    tagline: { ar: 'كرسي حمام معلّق بالحائط بتصميم مربّع نظيف', en: 'A wall-hung toilet with a clean square-edged design' },
    desc: { ar: 'كرسي حمام معلّق بالحائط بتصميم مربّع الحواف، يمنح الحمّام مظهراً عصرياً ويسهّل تنظيف الأرضية.', en: 'A wall-hung toilet with a square-edged design that gives the bathroom a modern look and makes floor cleaning easier.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'معلّق بالحائط', en: 'Wall-hung' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/toilet-wallhung-boxy.webp' },
  },
  {
    id: 'toilet-wallhung-wide', collection: 'toilets',
    title: { ar: 'كرسي حمام معلّق — عريض منحني', en: 'Wall-Hung Toilet — Wide Curve' },
    tagline: { ar: 'كرسي حمام معلّق بالحائط بجسم عريض منحني', en: 'A wall-hung toilet with a wide curved body' },
    desc: { ar: 'كرسي حمام معلّق بالحائط بجسم عريض منحني يمنح راحة إضافية ومظهراً عصرياً.', en: 'A wall-hung toilet with a wide curved body for extra comfort and a modern look.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'معلّق بالحائط', en: 'Wall-hung' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/toilet-wallhung-wide.webp' },
  },
  {
    id: 'toilet-wallhung-round', collection: 'toilets',
    title: { ar: 'كرسي حمام معلّق — منحني كلاسيكي', en: 'Wall-Hung Toilet — Classic Curve' },
    tagline: { ar: 'كرسي حمام معلّق بالحائط بخطوط منحنية كلاسيكية', en: 'A wall-hung toilet with classic curved lines' },
    desc: { ar: 'كرسي حمام معلّق بالحائط بخطوط منحنية كلاسيكية، يمنح الحمّام مظهراً نظيفاً ويسهّل تنظيف الأرضية.', en: 'A wall-hung toilet with classic curved lines that give the bathroom a clean look and make floor cleaning easier.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'معلّق بالحائط', en: 'Wall-hung' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/toilet-wallhung-round.webp' },
  },
  {
    id: 'toilet-onepiece-dualflush', collection: 'toilets',
    title: { ar: 'كرسي حمام قطعة واحدة — تصريف مزدوج', en: 'One-Piece Toilet — Dual Flush' },
    tagline: { ar: 'كرسي حمام أرضي من قطعة واحدة بزر تصريف مزدوج', en: 'A floor-standing one-piece toilet with a dual-flush button' },
    desc: { ar: 'كرسي حمام أرضي مصبوب من قطعة واحدة بزر تصريف مزدوج لتوفير استهلاك المياه، بتصميم كلاسيكي نظيف.', en: 'A floor-standing one-piece toilet with a dual-flush button to save water, in a clean classic design.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي', en: 'Floor-standing' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/toilet-onepiece-dualflush.webp' },
  },
  {
    id: 'toilet-onepiece-roundbutton', collection: 'toilets',
    title: { ar: 'كرسي حمام قطعة واحدة — زر دائري', en: 'One-Piece Toilet — Round Button' },
    tagline: { ar: 'كرسي حمام أرضي من قطعة واحدة بزر تصريف دائري', en: 'A floor-standing one-piece toilet with a round flush button' },
    desc: { ar: 'كرسي حمام أرضي مصبوب من قطعة واحدة بزر تصريف دائري علوي، سهل التنظيف وموفّر للمياه.', en: 'A floor-standing one-piece toilet with a round top-mounted flush button, easy to clean and water-efficient.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي', en: 'Floor-standing' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/toilet-onepiece-roundbutton.webp' },
  },
  {
    id: 'toilet-onepiece-stripbutton', collection: 'toilets',
    title: { ar: 'كرسي حمام قطعة واحدة — زر شريطي', en: 'One-Piece Toilet — Strip Button' },
    tagline: { ar: 'كرسي حمام أرضي من قطعة واحدة بزر تصريف شريطي مدمج', en: 'A floor-standing one-piece toilet with a slim inset flush strip' },
    desc: { ar: 'كرسي حمام أرضي مصبوب من قطعة واحدة بزر تصريف شريطي مدمج في الخزان، بتصميم عصري نظيف.', en: 'A floor-standing one-piece toilet with a slim flush strip inset into the tank, in a clean modern design.' },
    specs: [
      [{ ar: 'التركيب', en: 'Mount' }, { ar: 'أرضي', en: 'Floor-standing' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/toilet-onepiece-stripbutton.webp' },
  },
  // جاكوزي جديد
  {
    id: 'jacuzzi-single-grabrail', collection: 'jacuzzi',
    title: { ar: 'جاكوزي فردي بمقبض أمان ومسند رأس', en: 'Single Jacuzzi — Grab Rail & Headrest' },
    tagline: { ar: 'جاكوزي فردي بنفّاثات تدليك ومقبض أمان جانبي', en: 'A single jacuzzi with massage jets and a side grab rail' },
    desc: { ar: 'جاكوزي فردي بنفّاثات تدليك موزّعة، مسند رأس مبطّن، ومقبض أمان جانبي لسهولة الدخول والخروج.', en: 'A single jacuzzi with distributed massage jets, a padded headrest, and a side grab rail for easy entry and exit.' },
    specs: [
      [{ ar: 'السعة', en: 'Capacity' }, { ar: 'فرد واحد', en: 'Single occupant' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'أكريليك عالي الجودة', en: 'High-grade acrylic' }],
      [{ ar: 'المزايا', en: 'Features' }, { ar: 'نفّاثات تدليك ومقبض أمان', en: 'Massage jets and grab rail' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/jacuzzi-single-grabrail.webp' },
  },
  {
    id: 'jacuzzi-corner-twoseat', collection: 'jacuzzi',
    title: { ar: 'جاكوزي زاوية مزدوج بمسندين', en: 'Corner Jacuzzi — Two-Seat' },
    tagline: { ar: 'جاكوزي زاوية لشخصين بمسندي رأس منفصلين', en: 'A corner jacuzzi for two with separate headrests' },
    desc: { ar: 'جاكوزي زاوية بتصميم L مزدوج المقاعد، مزوّد بمسندي رأس منفصلين ونفّاثات تدليك موزّعة على طول الحوض.', en: 'An L-shaped corner jacuzzi for two, fitted with separate headrests and massage jets distributed along the tub.' },
    specs: [
      [{ ar: 'السعة', en: 'Capacity' }, { ar: 'شخصان', en: 'Two occupants' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'أكريليك عالي الجودة', en: 'High-grade acrylic' }],
      [{ ar: 'المزايا', en: 'Features' }, { ar: 'نفّاثات تدليك ومسندا رأس', en: 'Massage jets and dual headrests' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/jacuzzi-corner-twoseat.webp' },
  },
  {
    id: 'jacuzzi-corner-glass', collection: 'jacuzzi',
    title: { ar: 'جاكوزي زاوية بنافذة عرض زجاجية', en: 'Corner Jacuzzi — Glass View Panel' },
    tagline: { ar: 'جاكوزي زاوية بنافذة زجاجية أمامية وشاشة تحكّم', en: 'A corner jacuzzi with a front glass panel and control display' },
    desc: { ar: 'جاكوزي زاوية بنافذة زجاجية أمامية، شاشة تحكّم رقمية، ونفّاثات تدليك موزّعة على جسم الحوض.', en: 'A corner jacuzzi with a front glass viewing panel, a digital control display, and massage jets distributed across the tub body.' },
    specs: [
      [{ ar: 'السعة', en: 'Capacity' }, { ar: 'شخص إلى شخصين', en: 'One to two occupants' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'أكريليك عالي الجودة', en: 'High-grade acrylic' }],
      [{ ar: 'المزايا', en: 'Features' }, { ar: 'تحكّم رقمي ونافذة زجاجية', en: 'Digital control and glass panel' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/jacuzzi-corner-glass.webp' },
  },
  {
    id: 'jacuzzi-corner-digital', collection: 'jacuzzi',
    title: { ar: 'جاكوزي زاوية بشاشة تحكّم ومسندين', en: 'Corner Jacuzzi — Digital Panel' },
    tagline: { ar: 'جاكوزي زاوية بمسندي رأس وشاشة تحكّم رقمية', en: 'A corner jacuzzi with dual headrests and a digital control panel' },
    desc: { ar: 'جاكوزي زاوية بمسندي رأس مبطّنين، شاشة تحكّم رقمية، ونفّاثات تدليك متعدّدة موزّعة على جسم الحوض.', en: 'A corner jacuzzi with padded dual headrests, a digital control panel, and multiple massage jets distributed across the tub body.' },
    specs: [
      [{ ar: 'السعة', en: 'Capacity' }, { ar: 'شخص إلى شخصين', en: 'One to two occupants' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'أكريليك عالي الجودة', en: 'High-grade acrylic' }],
      [{ ar: 'المزايا', en: 'Features' }, { ar: 'تحكّم رقمي ومسندا رأس', en: 'Digital control and dual headrests' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/jacuzzi-corner-digital.webp' },
  },
  {
    id: 'jacuzzi-rect-waterfall', collection: 'jacuzzi',
    title: { ar: 'جاكوزي مستطيل بصنبور شلّال', en: 'Rectangular Jacuzzi — Waterfall Spout' },
    tagline: { ar: 'جاكوزي مستطيل بصنبور شلّال عريض ومسندين', en: 'A rectangular jacuzzi with a wide waterfall spout and dual headrests' },
    desc: { ar: 'جاكوزي مستطيل بصنبور شلّال عريض، مسندي رأس مبطّنين، ونفّاثات تدليك موزّعة توفّر تجربة استحمام فندقية.', en: 'A rectangular jacuzzi with a wide waterfall spout, padded dual headrests, and distributed massage jets for a hotel-style bathing experience.' },
    specs: [
      [{ ar: 'السعة', en: 'Capacity' }, { ar: 'شخصان', en: 'Two occupants' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'أكريليك عالي الجودة', en: 'High-grade acrylic' }],
      [{ ar: 'المزايا', en: 'Features' }, { ar: 'صنبور شلّال ونفّاثات تدليك', en: 'Waterfall spout and massage jets' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/jacuzzi-rect-waterfall.webp' },
  },
  {
    id: 'jacuzzi-corner-wood', collection: 'jacuzzi',
    title: { ar: 'جاكوزي مستطيل بشاشة تحكّم ومسندين', en: 'Rectangular Jacuzzi — Digital Control' },
    tagline: { ar: 'جاكوزي مستطيل بمسندين ولوحة تحكّم رقمية جانبية', en: 'A rectangular jacuzzi with dual headrests and a side digital control panel' },
    desc: { ar: 'جاكوزي مستطيل بمسندي رأس مبطّنين ولوحة تحكّم رقمية جانبية، مزوّد بنفّاثات تدليك متعدّدة.', en: 'A rectangular jacuzzi with padded dual headrests and a side digital control panel, fitted with multiple massage jets.' },
    specs: [
      [{ ar: 'السعة', en: 'Capacity' }, { ar: 'شخصان', en: 'Two occupants' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'أكريليك عالي الجودة', en: 'High-grade acrylic' }],
      [{ ar: 'المزايا', en: 'Features' }, { ar: 'تحكّم رقمي ونفّاثات تدليك', en: 'Digital control and massage jets' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/jacuzzi-corner-wood.webp' },
  },
  {
    id: 'jacuzzi-single-woodtray', collection: 'jacuzzi',
    title: { ar: 'جاكوزي فردي بمسند خشبي وسمّاعة', en: 'Single Jacuzzi — Wood-tone Tray & Speaker' },
    tagline: { ar: 'جاكوزي فردي بمسند علوي بلون خشبي وسمّاعة مدمجة', en: 'A single jacuzzi with a wood-tone top tray and a built-in speaker' },
    desc: { ar: 'جاكوزي فردي بمسند علوي بلون خشبي، سمّاعة مدمجة، وشاشة تحكّم رقمية، مع نفّاثات تدليك موزّعة على جسم الحوض.', en: 'A single jacuzzi with a wood-tone top tray, a built-in speaker, and a digital control display, with massage jets distributed across the tub body.' },
    specs: [
      [{ ar: 'السعة', en: 'Capacity' }, { ar: 'فرد واحد', en: 'Single occupant' }],
      [{ ar: 'الخامة', en: 'Material' }, { ar: 'أكريليك عالي الجودة', en: 'High-grade acrylic' }],
      [{ ar: 'المزايا', en: 'Features' }, { ar: 'سمّاعة مدمجة وتحكّم رقمي', en: 'Built-in speaker and digital control' }],
      [yrs, y5],
    ],
    finishes: ['white'], images: { white: '/products/jacuzzi-single-woodtray.webp' },
  },
]

// الأقسام الستة (ثنائية اللغة)
export const COLLECTIONS = [
  {
    id: 'mixers',
    name: { ar: 'الخلاطات', en: 'Mixers' }, short: { ar: 'الخلاطات', en: 'Mixers' },
    intro: { ar: 'خلاطات تجمع الدقّة والأناقة لتكون قلب مغسلتك ومطبخك.', en: 'Mixers that blend precision and elegance to be the heart of your basin and kitchen.' },
    features: [{ ar: 'تحكّم دقيق بالتدفّق', en: 'Precise flow control' }, { ar: 'تشطيب أسود مطفي', en: 'Matte black finish' }, { ar: 'خامات مقاومة للصدأ', en: 'Rust-resistant materials' }],
    accent: '#2f6fd6', bg: '#e4f0ff', image: '/products/mixer-chrome.webp',
    cover: '/categories/cat-1.webp',
    lifestyle: '/products/mixer-chrome-1.webp',
    types: [
      { id: 'curved', name: { ar: 'منحنى', en: 'Curved' } },
      { id: 'straight', name: { ar: 'مستقيم', en: 'Straight' } },
      { id: 'square', name: { ar: 'مربّع', en: 'Square' } },
      { id: 'cylindrical', name: { ar: 'أسطواني', en: 'Cylindrical' } },
    ],
  },
  {
    id: 'sprays',
    name: { ar: 'المروش', en: 'Showers' }, short: { ar: 'المروش', en: 'Showers' },
    intro: { ar: 'رؤوس مرشّات قابلة للتوجيه بضغط ماء متوازن وتركيب سهل.', en: 'Adjustable shower heads with balanced pressure and easy installation.' },
    features: [{ ar: 'رؤوس قابلة للتوجيه', en: 'Adjustable heads' }, { ar: 'ضغط ماء متوازن', en: 'Balanced pressure' }, { ar: 'تركيب سهل', en: 'Easy installation' }],
    accent: '#2f6fd6', bg: '#afd2ff', image: '/products/shower-gold.webp',
    cover: '/categories/cat-3.webp',
    lifestyle: '/categories/cat-3.webp',
    types: [
      { id: 'rain', name: { ar: 'مطري', en: 'Rain' } },
      { id: 'handheld', name: { ar: 'يدوي', en: 'Handheld' } },
      { id: 'column', name: { ar: 'عمود متكامل', en: 'Shower column' } },
      { id: 'concealed', name: { ar: 'سقفي مخفي', en: 'Concealed ceiling' } },
    ],
  },
  {
    id: 'bath',
    name: { ar: 'البانيو', en: 'Bathtub' }, short: { ar: 'البانيو', en: 'Bathtub' },
    intro: { ar: 'خلاطات بانيو جدارية بخطوط نحتية تمنح حمّامك حضوراً فندقياً.', en: 'Wall-mounted bath mixers with sculptural lines that give your bathroom a hotel presence.' },
    features: [{ ar: 'مخرج مزدوج', en: 'Dual outlet' }, { ar: 'محوّل انسيابي', en: 'Smooth diverter' }, { ar: 'تصميم جداري أنيق', en: 'Elegant wall design' }],
    accent: '#2f6fd6', bg: '#e4f0ff', image: '/products/faucet-bath-black.webp',
    cover: '/categories/cat-4.webp',
    lifestyle: '/products/collection-bath.webp',
    types: [
      { id: 'wall', name: { ar: 'جداري', en: 'Wall-mounted' } },
      { id: 'freestanding', name: { ar: 'حر قائم', en: 'Freestanding' } },
      { id: 'deck', name: { ar: 'حافة الحوض', en: 'Deck-mounted' } },
      { id: 'concealed', name: { ar: 'مخفي', en: 'Concealed' } },
    ],
  },
  {
    id: 'jacuzzi',
    name: { ar: 'الجاكوزي', en: 'Jacuzzi' }, short: { ar: 'الجاكوزي', en: 'Jacuzzi' },
    intro: { ar: 'جاكوزي فاخر بنفّاثات تدليك وإضاءة محيطة وتحكّم رقمي.', en: 'A luxurious jacuzzi with massage jets, ambient lighting and digital control.' },
    features: [{ ar: 'نفّاثات تدليك', en: 'Massage jets' }, { ar: 'إضاءة محيطة', en: 'Ambient lighting' }, { ar: 'تحكّم رقمي', en: 'Digital control' }],
    accent: '#2f6fd6', bg: '#d3e6ff', image: '/products/jacuzzi-white.webp',
    cover: '/products/jacuzzi-corner-glass.webp',
    lifestyle: '/products/jacuzzi-corner-glass.webp',
    types: [
      { id: 'freestanding', name: { ar: 'حر قائم', en: 'Freestanding' } },
      { id: 'corner', name: { ar: 'زاوية', en: 'Corner' } },
      { id: 'builtin', name: { ar: 'مدمج', en: 'Built-in' } },
      { id: 'spa', name: { ar: 'سبا مساج', en: 'Spa massage' } },
    ],
  },
  {
    id: 'accessories',
    name: { ar: 'ملحقات وتركيبات', en: 'Fittings & Accessories' }, short: { ar: 'ملحقات', en: 'Accessories' },
    intro: { ar: 'محابس ووصلات تكميلية بجودة موثوقة لإنهاء تركيب أدواتك الصحية بثقة.', en: 'Reliable-quality valves and connectors to complete your sanitary ware installation with confidence.' },
    features: [{ ar: 'إغلاق محكم وآمن', en: 'Tight, secure shut-off' }, { ar: 'خامة نحاسية مقاومة للصدأ', en: 'Rust-resistant brass' }, { ar: 'تركيب سريع', en: 'Quick installation' }],
    accent: '#2f6fd6', bg: '#dbe8ff', image: '/products/valve-corner-gr-bk.webp',
    cover: '/products/valve-corner-gr-bk.webp',
    lifestyle: '/products/valve-corner-gr-bk.webp',
  },
  {
    id: 'basins',
    name: { ar: 'المغاسل', en: 'Basins' }, short: { ar: 'المغاسل', en: 'Basins' },
    intro: { ar: 'مغاسل سيراميك بقاعدة أرضية أو معلّقة بالحائط، بتصاميم كلاسيكية وعصرية.', en: 'Ceramic basins, pedestal-mounted or wall-hung, in classic and modern designs.' },
    features: [{ ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }, { ar: 'تصاميم متعدّدة', en: 'Multiple designs' }, { ar: 'سهلة التنظيف', en: 'Easy to clean' }],
    accent: '#2f6fd6', bg: '#e4f0ff', image: '/products/basin-pedestal-oval.webp',
    cover: '/products/basin-wallhung-trumpet.webp',
    lifestyle: '/products/basin-wallhung-trumpet.webp',
    types: [
      { id: 'pedestal', name: { ar: 'بقاعدة أرضية', en: 'Pedestal' } },
      { id: 'wallhung', name: { ar: 'معلّقة بالحائط', en: 'Wall-hung' } },
    ],
  },
  {
    id: 'toilets',
    name: { ar: 'المراحيض', en: 'Toilets' }, short: { ar: 'المراحيض', en: 'Toilets' },
    intro: { ar: 'كراسي حمّام سيراميك أرضية من قطعة واحدة، ومعلّقة بالحائط، موفّرة للمياه.', en: 'One-piece floor-standing and wall-hung ceramic toilets, water-efficient.' },
    features: [{ ar: 'سيراميك عالي الجودة', en: 'High-grade ceramic' }, { ar: 'خيارات تصريف متعدّدة', en: 'Multiple trap options' }, { ar: 'موفّرة للمياه', en: 'Water-efficient' }],
    accent: '#2f6fd6', bg: '#dbe8ff', image: '/products/toilet-onepiece-dualflush.webp',
    cover: '/products/toilet-wallhung-wide.webp',
    lifestyle: '/products/toilet-wallhung-wide.webp',
    types: [
      { id: 'onepiece', name: { ar: 'قطعة واحدة', en: 'One-piece' } },
      { id: 'wallhung', name: { ar: 'معلّقة بالحائط', en: 'Wall-hung' } },
    ],
  },
]

export const collectionOf = (id) => COLLECTIONS.find((c) => c.id === id)
export const productsIn = (id) => PRODUCTS.filter((p) => p.collection === id)
export const productOf = (id) => PRODUCTS.find((p) => p.id === id)

export { FINISH }
